docker publishing pipeline for riverproui

diff --git a/.github/workflows/docker.yaml b/.github/workflows/docker.yaml
--- a/.github/workflows/docker.yaml
+++ b/.github/workflows/docker.yaml
@@ -9,21 +9,25 @@ on:
   pull_request:
     branches:
       - "master"
+  workflow_dispatch:
+    inputs:
+      ref:
+        description: "Tag to build (e.g. v0.1.0)"
+        required: true
 
 env:
   IMAGE_NAME: ${{ github.repository }}
   REGISTRY: ghcr.io
 
 jobs:
-  build:
-    name: Build Docker image
+  build-riverui:
+    name: "Build image: riverui"
     runs-on: ubuntu-latest
     strategy:
       matrix:
         docker_platform:
           - linux/amd64
           - linux/arm64
-          - linux/arm64/v8
     outputs:
       tags: ${{ steps.meta.outputs.tags }}
       labels: ${{ steps.meta.outputs.labels }}
@@ -36,6 +40,8 @@ jobs:
     steps:
       - name: Checkout
         uses: actions/checkout@v4
+        with:
+          ref: ${{ inputs.ref || github.ref }}
 
       - name: Prepare
         run: |
@@ -59,7 +65,7 @@ jobs:
         id: meta
         uses: docker/metadata-action@v5
         with:
-          images: ghcr.io/${{ github.repository }}
+          images: ghcr.io/${{ env.IMAGE_NAME }}
           labels: |
             org.opencontainers.image.source=https://github.com/riverqueue/riverui
             org.opencontainers.image.description="River UI is a web-based user interface for River, a fast and reliable background job system."
@@ -69,6 +75,7 @@ jobs:
             type=ref,event=pr
             type=semver,pattern={{version}}
             type=semver,pattern={{major}}.{{minor}}
+            type=raw,value=latest,enable=${{ startsWith(github.ref, 'refs/tags/v') }}
 
       - name: Build and push to GitHub Container Registry
         id: build
@@ -98,30 +105,115 @@ jobs:
       - name: Upload digest
         uses: actions/upload-artifact@v4
         with:
-          name: digests-${{ env.PLATFORM_PAIR }}
+          name: digests-oss-${{ env.PLATFORM_PAIR }}
           path: /tmp/digests/*
           if-no-files-found: error
           retention-days: 1
 
-  merge:
-    name: Merge and publish image manifests
+  build-riverproui:
+    name: "Build image: riverproui"
     runs-on: ubuntu-latest
-    needs:
-      - build
+    outputs:
+      tags: ${{ steps.meta-pro.outputs.tags }}
+      digest: ${{ steps.build.outputs.digest }}
     permissions:
+      attestations: write
       contents: read
       id-token: write
-      packages: write
+    env:
+      ECR_CACHE_AWS_REGION: "us-east-2"
 
     steps:
       - name: Checkout
         uses: actions/checkout@v4
+        with:
+          ref: ${{ inputs.ref || github.ref }}
 
+      - name: Login to ECR
+        uses: docker/login-action@v3
+        with:
+          registry: ${{ secrets.ECR_CACHE_AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.ECR_CACHE_AWS_REGION }}.amazonaws.com
+          username: ${{ secrets.ECR_CACHE_AWS_ACCESS_KEY_ID }}
+          password: ${{ secrets.ECR_CACHE_AWS_SECRET_ACCESS_KEY }}
+
+      - name: Set TAG
+        run: echo "TAG=${{ inputs.ref || github.ref_name }}" >> $GITHUB_ENV
+
+      - name: Validate TAG
+        if: startsWith(github.ref, 'refs/tags/v') || github.event_name == 'workflow_dispatch'
+        run: |
+          if [[ ! "$TAG" == v* ]]; then
+            echo "Tag must start with 'v'"
+            exit 1
+          fi
+
+      - name: Set up QEMU
+        uses: docker/setup-qemu-action@v3
+
+      - name: Set up Docker Buildx
+        uses: docker/setup-buildx-action@v3
+
+      - name: Docker meta for Pro
+        id: meta-pro
+        uses: docker/metadata-action@v5
+        with:
+          images: riverqueue.com/riverproui
+          labels: |
+            org.opencontainers.image.source=https://github.com/riverqueue/riverui
+            org.opencontainers.image.description="River UI Pro is a web-based user interface for River, with pro features."
+            org.opencontainers.image.licenses=MPL-2.0
+          # TODO: type=ref are temporary for testing
+          tags: |
+            type=ref,event=branch
+            type=ref,event=pr
+            type=semver,pattern={{version}}
+            type=semver,pattern={{major}}.{{minor}}
+            type=raw,value=latest,enable=${{ startsWith(github.ref, 'refs/tags/v') }}
+
+      - name: Build and export to OCI
+        id: build
+        uses: docker/build-push-action@v6
+        with:
+          context: .
+          file: Dockerfile.pro
+          pull: true
+          platforms: linux/amd64,linux/arm64
+          labels: ${{ steps.meta-pro.outputs.labels }}
+          cache-from: type=registry,ref=${{ secrets.ECR_CACHE_AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.ECR_CACHE_AWS_REGION }}.amazonaws.com/riverqueue/riverproui:cache
+          cache-to: type=registry,mode=max,image-manifest=true,oci-mediatypes=true,ref=${{ secrets.ECR_CACHE_AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.ECR_CACHE_AWS_REGION }}.amazonaws.com/riverqueue/riverproui:cache
+          outputs: type=oci,dest=/tmp/oci,tar=false
+          secrets: |
+            "riverpro_credential=${{ secrets.RIVERPRO_GO_MOD_CREDENTIAL }}"
+
+      - name: Generate artifact attestation
+        uses: actions/attest-build-provenance@v1
+        with:
+          push-to-registry: false
+          subject-digest: ${{ steps.build.outputs.digest }}
+          subject-name: riverqueue.com/riverproui
+
+      - name: Upload OCI artifact
+        uses: actions/upload-artifact@v4
+        with:
+          name: pro-oci
+          path: /tmp/oci
+          retention-days: 1
+
+  merge-riverui:
+    name: "Merge manifests: riverui"
+    runs-on: ubuntu-latest
+    needs:
+      - build-riverui
+    permissions:
+      contents: read
+      packages: write
+
+    steps:
       - name: Download digests
         uses: actions/download-artifact@v4
         with:
           path: /tmp/digests
-          pattern: digests-*
+          pattern: digests-oss-*
           merge-multiple: true
 
       - name: Set up Docker Buildx
@@ -138,7 +230,7 @@ jobs:
         id: meta
         uses: docker/metadata-action@v5
         with:
-          images: ghcr.io/${{ env.IMAGE_NAME }}
+          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
           labels: |
             org.opencontainers.image.source=https://github.com/riverqueue/riverui
             org.opencontainers.image.description="River UI is a web-based user interface for River, a fast and reliable background job system."
@@ -148,13 +240,89 @@ jobs:
             type=ref,event=pr
             type=semver,pattern={{version}}
             type=semver,pattern={{major}}.{{minor}}
+            type=raw,value=latest,enable=${{ startsWith(github.ref, 'refs/tags/v') }}
 
       - name: Create manifest list and push
         working-directory: /tmp/digests
         run: |
-          docker buildx imagetools create $(jq -cr '.tags | map("-t " + .) | join(" ")' <<< "$DOCKER_METADATA_OUTPUT_JSON") \
+          docker buildx imagetools create \
+            --annotation "index:org.opencontainers.image.source=https://github.com/riverqueue/riverui" \
+            --annotation "index:org.opencontainers.image.description=River UI is a web-based user interface for River, a fast and reliable background job system." \
+            --annotation "index:org.opencontainers.image.licenses=MPL-2.0" \
+            $(jq -cr '.tags | map("-t " + .) | join(" ")' <<< "$DOCKER_METADATA_OUTPUT_JSON") \
             $(printf '${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}@sha256:%s ' *)
 
-      - name: Inspect image
+  publish-riverproui:
+    name: "Publish Docker image: riverproui"
+    runs-on: ubuntu-latest
+    needs:
+      - build-riverproui
+
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v4
+        with:
+          ref: ${{ inputs.ref || github.ref }}
+
+      - name: Download OCI artifact
+        uses: actions/download-artifact@v4
+        with:
+          name: pro-oci
+          path: /tmp/oci
+
+      - name: DEBUG OCI Directory Structure
+        run: ls -R /tmp/oci || echo "Directory not found"
+
+      - name: Install jq
+        run: sudo apt-get update && sudo apt-get install -y jq
+
+      - name: Install AWS CLI
+        uses: unfor19/install-aws-cli-action@v1
+        with:
+          version: 2
+          verbose: false
+          arch: amd64
+
+      - name: Configure AWS CLI
         run: |
-          docker buildx imagetools inspect ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.meta.outputs.version }}
+          aws configure set aws_access_key_id ${{ secrets.R2_ACCESS_KEY_ID }}
+          aws configure set aws_secret_access_key ${{ secrets.R2_SECRET_ACCESS_KEY }}
+          aws configure set default.region auto
+
+      - name: Sync blobs to R2
+        # TODO: temporary for testing
+        # if: startsWith(github.ref, 'refs/tags/v') || github.event_name == 'workflow_dispatch'
+        env:
+          DOCKER_RELEASE_STORAGE_BUCKET: ${{ vars.DOCKER_RELEASE_STORAGE_BUCKET }}
+          REPO_NAME: riverqueue.com/riverproui
+          ENDPOINT_URL: ${{ secrets.R2_DOCKER_RELEASES_ENDPOINT_URL }}
+        run: |
+          aws s3 cp /tmp/oci/blobs/sha256/ s3://$DOCKER_RELEASE_STORAGE_BUCKET/$REPO_NAME/blobs/sha256/ --recursive --endpoint-url $ENDPOINT_URL
+
+      - name: Upload manifest by digest
+        # TODO: temporary for testing
+        # if: startsWith(github.ref, 'refs/tags/v') || github.event_name == 'workflow_dispatch'
+        env:
+          DOCKER_RELEASE_STORAGE_BUCKET: ${{ vars.DOCKER_RELEASE_STORAGE_BUCKET }}
+          REPO_NAME: riverqueue.com/riverproui
+          ENDPOINT_URL: ${{ secrets.R2_DOCKER_RELEASES_ENDPOINT_URL }}
+        run: |
+          MANIFEST_DIGEST=$(sha256sum /tmp/oci/index.json | awk '{print $1}')
+          aws s3 cp /tmp/oci/index.json s3://$DOCKER_RELEASE_STORAGE_BUCKET/$REPO_NAME/manifests/sha256:$MANIFEST_DIGEST --content-type "application/vnd.docker.distribution.manifest.list.v2+json" --endpoint-url $ENDPOINT_URL
+
+      - name: Upload tagged manifests
+        # TODO: temporary for testing
+        # if: startsWith(github.ref, 'refs/tags/v') || github.event_name == 'workflow_dispatch'
+        env:
+          DOCKER_RELEASE_STORAGE_BUCKET: ${{ vars.DOCKER_RELEASE_STORAGE_BUCKET }}
+          REPO_NAME: riverqueue.com/riverproui
+          ENDPOINT_URL: ${{ secrets.R2_DOCKER_RELEASES_ENDPOINT_URL }}
+        run: |
+          # Extract tags from the build job output (newline-separated)
+          echo '${{ needs.build-riverproui.outputs.tags }}' > tags.txt
+          while IFS= read -r TAG; do
+            if [ -n "$TAG" ]; then
+              SHORT_TAG="${TAG#riverqueue.com/riverproui:}"
+              aws s3 cp /tmp/oci/index.json s3://$DOCKER_RELEASE_STORAGE_BUCKET/$REPO_NAME/manifests/$SHORT_TAG --content-type "application/vnd.docker.distribution.manifest.list.v2+json" --endpoint-url $ENDPOINT_URL
+            fi
+          done < tags.txt
